eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: ${eureka_url:http://192.168.29.6:8761/eureka}
  instance:
    hostname: 192.168.29.6
    prefer-ip-address: true
  #  hostname: localhost
     
    
